default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: cebolla_dev
  password: cebolla_dev
  database: cebolla_dev

test:
  <<: *default
  host: localhost
  username: cebolla_test
  password: cebolla_test
  database: cebolla_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
